---
title: Fundamentals
format:
  html:
    toc: true
    toc-expand: 3
---

## Paul's notes

- [Digital representation of data](digital_representation_of_data.qmd)
- [Control flow & Complex data types](control_flow_and_complex_data_types.qmd)
- [Functions, File input & output](functions_file_io.qmd)

## Python Fundamentals

- Learning with Python 3 chapter 1: [The way of the program](https://openbookproject.net/thinkcs/python/english3e/way_of_the_program.html)
- Learning with Python 3 chapter 2: [Variables, expressions and statements](https://openbookproject.net/thinkcs/python/english3e/variables_expressions_statements.html)
- Python for Data Analysis chapter 1: [Preliminaries](https://wesmckinney.com/book/preliminaries.html)
- Python for Data Analysis chapter 2: [Python Language Basics, iPython, and Jupyter Notebooks](https://wesmckinney.com/book/python-basics.html)
- NumPy: [the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)
- Python for Data Analysis chapter 4: [NumPy Basics: Arrays and Vectorized Computation](https://wesmckinney.com/book/numpy-basics.html)
- a fun coding challenge: [Advent of Code 2015, Day 6](https://adventofcode.com/2015/day/6) (hint: use a 1000x1000 2D array)

### other useful readings

- [The way of the program](https://openbookproject.net/thinkcs/python/english3e/way_of_the_program.html)
- [Variables, expressions, and statements](https://greenteapress.com/thinkpython2/html/thinkpython2003.html)
- [Python Language Basics](https://wesmckinney.com/book/python-basics.html#tut_basics)
- [Files & the File System](https://mptc.io/content/03-content-shell.html) by Kieran Healy
- [How to Name Files](https://youtu.be/ES1LTlnpLMk) video by Jenny Bryan

### Conditionals, Iteration, & Control Flow

- Learning with Python 3 chapter 5: [Conditionals](https://openbookproject.net/thinkcs/python/english3e/conditionals.html#conditionals)
- Learning with Python 3 chapter 7: [Iteration](https://openbookproject.net/thinkcs/python/english3e/iteration.html#iteration)
- Python for Data Analysis chapter 3: [Built-in Data Structures, Functions, and Files](https://wesmckinney.com/book/python-builtin.html)
- Python for Data Analysis chapter 4: [NumPy Basics: Arrays and Vectorized Computation](https://wesmckinney.com/book/numpy-basics.html)
- Python for Data Analysis chapter 5: [Getting Started with pandas](https://wesmckinney.com/book/pandas-basics.html)
- [Conditionals and recursion](https://greenteapress.com/thinkpython2/html/thinkpython2006.html) (you can ignore for now the section on recursion)
- [Control Flow](https://wesmckinney.com/book/python-basics.html#control_flow)

### File i/o

- [NumPy reading & writing files](https://numpy.org/devdocs/user/how-to-io.html)
- [NumPy data types](https://numpy.org/doc/2.1/user/basics.types.html)
- [pandas IO tools](https://pandas.pydata.org/docs/user_guide/io.html)
- [Python reading and writing files](https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files)
- Python for Data Analysis chapter 6: [Data Loading, Storage, and File Formats](https://wesmckinney.com/book/accessing-data.html)
- [Project Structure](https://djnavarro.net/slides-project-structure/#1), file naming, folders, etc... by Danielle Navarro
