---
title: Graphics & Figures
format:
  html:
    toc: true
    toc-expand: 3
---

Read [Chapter 9, Plotting and Visualization](https://wesmckinney.com/book/plotting-and-visualization) of Python for Data Analysis by Wes McKinney, for a great introduction to the kinds of plots you can make, and a basic subset of plotting commands. It's a great place to start.

Python has several libraries that can be used for generating graphics. The most popular ones are `matplotlib` and `seaborn`.

- Matplotlib: [tutorials](https://matplotlib.org/stable/tutorials/index)
- [The Python Graph Gallery](https://www.python-graph-gallery.com/)
- [Seaborn](https://seaborn.pydata.org/): statistical data visualization

Matplotlib is more or less a copy of MATLAB's plotting capabilities, so if you are familiar with MATLAB, you will feel at home with matplotlib.

Seaborn is a high-level interface for drawing attractive and informative statistical graphics. It's a little bit like `ggplot2` in R. It's great for plotting data that's in a tabular format.

