---
title: A Note about Homeworks
format:
  html:
    toc: false
---

The reason I assign homework to you each week is **not** because I want to see your homework.

The goal of homework isn't to hand in each assignment.

The purpose of homework assignments is for you to **do the intellectual work** required to write code that satisfies each homework assignment.

If you choose to use an AI tool (e.g. ChatGPT, or Claude Code, or GitHub CoPilot, or others) to write your homework code then you will probably get a very good grade in this course but you will not have done the intellectual work, and in this way there will be no reason for you to have taken this course.

In my experience (which is more than three decades in a university environment), reading code that someone else wrote (or that an AI tool wrote) is not a substitute for doing the intellectual work involved in producing your own code from scratch. It simply isn't.

If you take this course, and you get a good grade, your supervisors / bosses / collaborators will expect you to have mastered the material and skills that are advertised in the course outline, and that are reflected in the homework assignments that you hand in.

The grade is not the goal. The intellectual work is the goal. If you don't want to do the intellectual work, don't take the course. It would be a waste of your time and mine.

If you are having difficulty with the intellectual work, come and see me or the TA, we will be absolutely pleased to help!

---Paul

