---
title: Scientific Computing FW25 (Jan-Apr 2026)
format:
  html:
    toc: false
---

<table class="info">
  <tr>
    <td class=align="right" style="text-align:right; padding: 7px;">**URL**</td>
    <td><a href="https://gribblelab.org/9040">www.gribblelab.org/9040</a></td>
  </tr>
  <tr>
    <td class=align="right" style="text-align:right; padding: 7px;">**Instructor**</td>
    <td>Paul Gribble (<pgribble@uwo.ca>)</td>
  </tr>
  <tr>
    <td style="text-align:right; padding: 7px;">**Classes**</td>
    <td>Mondays & Thursdays, 9:30 am - 11:00 am in [WIRB 1110](https://wts.uwo.ca/ctg/classrooms/western_interdisciplinary_research_building/wirb_1110.html)</td>
  </tr>
  <tr>
    <td class=align="right" style="text-align:right; padding: 7px;">**TA**</td>
    <td>Anthony Cruz (<acruz27@uwo.ca>)</td>
  </tr>
</table>

---

- [A note about homeworks](homeworks.qmd)

---

## Schedule

<div class="mt-4 table-bordered">

|     Date     |                                      Topic / Notes                                       |      Homework       |
| ------------ | ---------------------------------------------------------------------------------------- | :-----------------: |
| Jan 5/8      | [Intro](intro.qmd)  ;  [Setup](setup.qmd) ; [uv](uv.qmd) ; [Git](git.qmd)                |          -          |
| Jan 12/15    | [Fundamentals](fundamentals.qmd) (expressions & variables)                               | [HW01](hw/hw01.qmd) |
| Jan 19/22    | [Fundamentals](fundamentals.qmd) (loops & conditionals)                                  | [HW02](hw/hw02.qmd) |
| Jan 26/29    | [Fundamentals](fundamentals.qmd) (data structures & functions)                           | [HW03](hw/hw03.qmd) |
| Feb 2/5      | [Fundamentals](fundamentals.qmd) (NumPy & File i/o)                                      | [HW04](hw/hw04.qmd) |
| Feb 9/12     | [Object Oriented Programming (OOP)](oop.qmd)                                             | [HW05](hw/hw05.qmd) |
| Feb 16/19    | *no classes* (reading week)                                                              |          -          |
| Feb 23/26    | [Graphical Displays of Data](graphics.qmd)                                               | [HW06](hw/hw06.qmd) |
| Mar 2/5      | Reproducibility/Replicability I: [plaintext authoring](plaintext-authoring.qmd)          | [HW07](hw/hw07.qmd) |
| Mar 9/12     | *no classes* (Paul away)  Reproducibility/Replicability II: [clean code](clean_code.qmd) |          -          |
| Mar 16/19    | Sampling, Signal Processing, & Filtering Data                                            |        HW08         |
| Mar 23/26    | Statistical Thinking & Inferential Statistical Tests                                     |        HW09         |
| Mar 30/Apr 2 | Fitting Models to Data                                                                   |        HW10         |
| Apr 6/Apr 9  | Simulating Dynamical Systems                                                             |          -          |

: {tbl-colwidths="[15,75,10]"}
</div>

---

- [concepts](concepts.qmd) covered each week
- [sample code](code.qmd) produced in class

## Readings
- [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney
- [The Curious Coder's Guide to Git](https://matthew-brett.github.io/curious-git/index.html) by Matthew Brett
- [Better Code, Better Science](https://poldrack.github.io/BetterCodeBetterScience/) by Russ Poldrack
