---
title: Introduction to the Course
format:
  html:
    toc: true
    toc-expand: 1
    page-layout: full
---

Welcome! I'm glad you're here.

This is **Psychology 9040: Scientific Computing**, for FW25, Jan-Apr 2026.

Bring your computer to class! We will be writing code.

Course website: [https://gribblelab.org/9040](https://gribblelab.org/9040)

---

## Course Goals

In this one-semester graduate course you will learn skills in scientific computing—tools and techniques that you can use in your own research. You will learn to program using **Python**, which is a high-level programming language with many libraries that provide a rich ecosystem for scientific computing. If you want to use a different language in the course you are welcome to but I will focus on Python in class. Having said that, as much as I can I will teach concepts in a way that are language-agnostic.

The course is designed to achieve three primary goals:

1. You will learn to **write code** in a high-level language (Python)
2. You will learn to **think computationally and algorithmically** about data analysis
3. You will learn some common **data analysis techniques**, which will give you a foundation from which to learn more complex scientific computing skills to suit your own research goals


## Topics

In the first part of the course you will **learn how to write code**. The topics we will cover are common to any high-level language including Python, MATLAB, R, Javascript, C, Julia, Go, Swift, etc. All high level languages have things like numbers, strings, arrays, loops, if-statements. Languages differ in their syntax, in the names of common functions, and sometimes in some other subtle ways (e.g. passing by reference vs passing by value) but otherwise, all high-level languages basically work in the same way. Learning these **fundamental concepts of high-level programming languages** using one language will enable you to learn other languages as well in the future.

The other aspect of programming that you will learn is how to think algorithmically about solving problems and completing tasks with computers. In general there are two reasons to use a computer to perform a given task, (1) because the task would take too long by hand (e.g. churning through processing a huge amount of data), and (2) because the computer can do something clever that you cannot do yourself (e.g. applying complex algorithms to a dataset).

In learning the fundamentals of high-level programming languages (data types, loops, conditionals, etc) we will sometimes practice writing code to solve little toy problems. This will start to teach you how to think algorithmically. Think about it like learning to play a musical instrument. You don't start by learining to play Beethoven. You start learning basic skills by playing scales, arpeggios, different key signatures, etc. Building up basic skills using toy problems is a convenient path towards using coding skills to solve real-world programming problems in the context of your own thesis research.

We will also practice and learn by using code to answer questions about data. Some of the data will be from real experiments and some will be fictitious. The goal will be to answer a series of questions by writing code that performs operations on the data (reorganization, summarising, counting, calculating, processing, plotting, etc) and writing a short summary of your findings. This mimics how you will be using your coding skills in your own research going forward.

### Fundamentals of Coding

- digital representation of data
- basic data types, operators, & expressions
- control flow & conditionals
- functions
- complex data types
- file input & output
- graphical displays of data
- object oriented programming (OOP)

### Reproducibility & Replicability

- Python venvs (virtual environments)
- Code versioning using Git & GitHub
- organization of code and data
- data analysis workflow

### Topics in Data Analysis

- sampling, signal processing, & filtering data
- statistical tests (parametric vs resampling/boostrapping/randomization)
- fitting models to data
- simulating dynamical systems

By building upon the foundational knowledge and skills you have acquired in this course, you will be able to learn other techniques in programming and in data analysis as your scientific research progresses.

## MacOS, Windows, or Linux?

Yes.

Sort of.

If you are using Unix/Linux, good news, you are all set, just some configuration things and some package installs and your computing environment will be ready for a modern course in coding / scientific computing.

If you are using MacOS, also good news, you may not know it but MacOS is based on a Unix variant, so with some small configuration things and some package installs, you will also be ready.

If you are using Windows, also good news, sort of, you will not need to use Windows! Let me explain. Something we will cover in this course is learning to use the terminal, learning about file systems, files, directories, and so on. On Linux/Unix and on MacOS (which is based on Unix) this is straightforward and you won't need to do anything particularly special. On Windows however you will need to do some initial setup to install something called the *Windows Subsystem for Linux* (WSL). This will enable you to launch a Linux session within Windows, and follow along in the course with everyone else. It's not such a big deal. Instructions are below.

PS: Personally I am most familiar with MacOS and Unix/Linux. I am quite unfamiliar with Windows.

### Unix/Linux

x

### MacOS

x

### Windows

x

## Python

We will be using Python in this course.

- download and install [Python](https://www.python.org/downloads/)

## Code Editor

Python code lives in plain text files that by convention have a `.py` extension, and you can view and edit them in any editor you want. There are many to choose from. I use Visual Studio Code which is free and available on MacOS, Windows, and Linux. You can use whatever you wish. In class I will be using Visual Studio Code, and I will show you how to use some of its more useful features for Python programming and data analysis.

- download and install [Visual Studio Code](https://code.visualstudio.com)

## Git/GitHub

We will be covering code versioning using Git and GitHub, so you should:

- download and install [Git](https://git-scm.com) on your computer
- sign up for a (free) [GitHub](https://www.github.com) account

## Check your setup

Assuming you have installed Python and VSCode:

1. create a new folder somewhere on your computer's file system and name it `Psych_9040`
2. launch VSCode
3. in the welcome screen there is an item under "Start" called "Open Folder ..." --- click it and navigate to the `Psych_9040` folder you created in step 1 above, and select it
4. now click on "New File ..." to create a new empty file, select "Text File" from the dropdown menu
4. In the VSCode "File" menu select "Save" and name the file `hello.py`; VSCode may ask you if you want to install the Python extension, click Yes
5. If you didn't get asked about installing the Python extension, do it manually: type CMD-Shift-P (MacOS) or CTRL-Shift-P (Windows/Linux) to launch the Command Palette and enter `Extensions: Install Extensions` and select the item from the dropdown menu by clicking it with the mouse or by typing Enter/Return; the Extension browser will have opened as a column on the left hand side of the VSCode window. At the top there is an empty text entry field. Type `Python`; click "Install" on the one called "Python" (Python extension for Visual Studio Code) from Microsoft
6. type the following in your `hello.py` file:

```{python}
#| eval: false
import numpy as np

x = np.array ([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
y = np.sum(x)
print(f"the sum of {x} is {y}")
```

7. launch the Command Palette and type in `Python: Create Environment` and select that item in the dropdown list

8. select the "Venv" option to create a `.venv` virtual environment in the current workspace

9. select your preferred Python interpreter from the dropdown list

10. bring up the Command Palette again and type `Terminal: Create New Terminal` and select it; (note: if you are on Windows, click the down-arrow next to the `+` and select "Select Default Profile" and then select "Command Prompt")... then close the terminal and re-open it via the Command Palette

11. in the Terminal that opens up, type `pip install numpy` and then Return/Enter

12. now type `python hello.py` and Return/Enter

You should see the following output in the Terminal:

```{python}
#| echo: false
import numpy as np

x = np.array ([2, 3, 5, 7, 11, 13, 17, 19, 23, 29])
y = np.sum(x)
print(f"the sum of {x} is {y}")
```


