{
  "hash": "dc8f603f23a04466987e9ff92e069eec",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Statistics: Parametric tests\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n---\n\n## Statsmodels & Scipy.stats\n\nThe `statsmodels` package is a Python module that provides classes and functions for many different kinds of statistical tests. It is a good alternative to the `scipy.stats` module, which we have been using so far. The `statsmodels` package is more comprehensive and has more options for the tests. It also has a more user-friendly interface. Here is a semi-organized list of various tests and tools [Statistics stats](https://www.statsmodels.org/dev/stats.html).\n\nOn the other hand `scipy.stats` is more widely used and has a more extensive documentation. So it is a good idea to know how to use both. Here is a list of the tests and tools in `scipy.stats` [scipy.stats](https://docs.scipy.org/doc/scipy/reference/stats.html).\n\nWelcome to the world of Python 🤷\n\n## Common Parametric Statistical Tests\n\nLet's go over some of the tests you have probably learned about in your statistics classes in the past.\n\nFirst we will load packages that we will be using:\n\n::: {#e63d36be .cell execution_count=1}\n``` {.python .cell-code}\nimport statsmodels.stats.weightstats as sm\nimport numpy as np\nimport matplotlib.pyplot as plt\n```\n:::\n\n\n## One-sample t-test\n\nLet's generate a sample of size n=10 from a normal distribution with mean 0 and standard deviation 1:\n\n::: {#a74514f4 .cell execution_count=2}\n``` {.python .cell-code}\nnp.random.seed(9040)\nn = 10\npopmean = 0\npopsd = 1\ny = np.random.normal(popmean, popsd, n)\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\narray([ 1.6906368 , -0.75271818,  0.26192835,  0.03147374, -0.41998303,\n        0.90818203,  1.81479305,  0.66291534, -0.97879878, -1.10367887])\n```\n:::\n:::\n\n\nNow let's imagine we want to conduct a statistical test of the null hypothesis that the mean of the population from which the same was drawn is equal to 0. We can do this using the `ztest()` function:\n\n::: {#9f94b85d .cell execution_count=3}\n``` {.python .cell-code}\ntstat, pvalue = sm.ztest(x1=y, x2=None, value=0, alternative='two-sided')\n\nprint(f\"t({n-1}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(9) = 0.636, p = 0.525\n```\n:::\n:::\n\n\nThe results of our statistical test show that the t statistic is 0.636 on 9 degrees of freedom, and the p-value is 0.525. This p-value is far above any commonly used significance level (e.g. .05), so we fail to reject the null hypothesis that the mean of the population is equal to 0.\n\nMore precisely, the p-value indicates that the probability of observing a t statistic as large as 0.636 or larger if we were to take a random sample of size n=10 from a population with a mean of zero, is 0.525. This is a very large probability, so we fail to reject the null hypothesis.\n\nLet's repeat the \"experiment\" this time taking a different random sample:\n\n::: {#9a07eaea .cell execution_count=4}\n``` {.python .cell-code}\nnp.random.seed(1236)\nn = 10\npopmean = 0\npopsd = 1\ny = np.random.normal(popmean, popsd, n)\ny\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\narray([-0.09375848, -1.69935067,  0.40455707, -1.39563456, -1.35254219,\n       -0.76516263, -1.3732163 , -2.00312241,  0.33949538, -0.07418577])\n```\n:::\n:::\n\n\n::: {#bfa97525 .cell execution_count=5}\n``` {.python .cell-code}\ntstat, pvalue = sm.ztest(x1=y, x2=None, value=0, alternative='two-sided')\n\nprint(f\"t({n-1}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(9) = -2.869, p = 0.004\n```\n:::\n:::\n\n\nThis time the t statistic is -2.869 which is much larger (farther from zero) and the p-value is much smaller, 0.004. If this were a real experiment, we would reject the null hypothesis that the mean of the population is equal to 0. We would do this because the probability of obtaining a t statistic as large (different than zero) as -2.869 if we were to take a random sample of size n=10 from a population with a mean of zero, is only 0.004. This is a very small probability, so we would reject the null hypothesis.\n\nRemember in a real experiment we never know if the null hypothesis is true or false. All we can ever do is compute the p-value, the probability of obtaining a test statistic as large or larger than the one we obtained, *if the null hypothesis were true*. If that p-value is small (e.g. less than .05, or less than .01), then we conclude we're not that lucky! We reject the null hypothesis.\n\n### The role of sample size: simulations\n\nRemember from your introductory statistics class(es) that the sample size plays a huge role in the range of sample means that one is likely to obtain under the null hypothesis. Let's see this in action using some simulations.\n\nWe will take a random sample of size n from a population with a true mean of zero. Then we will compute the sample mean. We will repeat this 10000 times.\n\nWe will repeat the 10000 simulatons for different sample sizes n=10, n=50, n=10, n=1000.\n\n::: {#73682755 .cell execution_count=6}\n``` {.python .cell-code}\nsamp_sizes = [10, 50, 100, 1000]\nnsims = 10000\nfor n in samp_sizes:\n    ymeans = np.zeros(nsims)\n    for i in range(nsims):\n        y = np.random.normal(0, 1, n)\n        ymeans[i] = np.mean(y)\n    plt.hist(ymeans, bins=50)\nplt.xlim = (-1.1, 1.1)\nplt.legend(samp_sizes)\nplt.title(\"n=10, n=50, n=100, n=1000\")\nplt.xlabel(\"Sample mean\")\nplt.ylabel(\"Frequency\")\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-7-output-1.png){width=662 height=470}\n:::\n:::\n\n\nYou can clearly see that as the sample size increases, the range of sample means we get, *under the null hypothesis*, gets smaller. This is why the p-value is so much smaller for a given t statistic when the sample size is larger. It reflects the fact that is is more unlikely to see a given non-zero sample mean (and non-zero t statistic) as the sample size increases.\n\nFor example if we did one experiment with a sample size of n=10 and we obtained a sample mean of 0.60, what is the probability of obtaining this under the null hypothesis that the true mean of the population from which the random sample was taken, is zero? That is the p-value. You can see in the plot below that it is pretty unlikely to happen.\n\n::: {#7be48b3a .cell execution_count=7}\n``` {.python .cell-code}\nnsims = 10000\nn = 10\nymeans = np.zeros(nsims)\nfor i in range(nsims):\n    y = np.random.normal(0, 1, n)\n    ymeans[i] = np.mean(y)\nplt.hist(ymeans, bins=50)\nplt.xlim = (-1.1, 1.1)\nplt.axvline(0.60, color=\"red\")\nplt.title(\"n=10, n=50, n=100, n=1000\")\nplt.xlabel(\"Sample mean\")\nplt.ylabel(\"Frequency\")\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-8-output-1.png){width=662 height=470}\n:::\n:::\n\n\nWe can estimate this probability by counting the number of simulated cases in which the sample mean was equal or greater than 0.60, and dividing by the total number of simulated cases. This is the empirical p-value.\n\n::: {#8164714c .cell execution_count=8}\n``` {.python .cell-code}\npvalue_empirical = len(ymeans[ymeans >= 0.60]) / len(ymeans)\n\nprint(f\"p-value = {pvalue_empirical:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\np-value = 0.029\n```\n:::\n:::\n\n\nWe can of course compute this p-value using a parametric statistical test, without having to run 10,000 simulations, e.g. a one-sample t-test, as above:\n\n::: {#ac6b2e2e .cell execution_count=9}\n``` {.python .cell-code}\nnp.random.seed(8329) # chosen by me strategically to get a sample mean of 0.60\ny = np.random.normal(0, 1, 10) # run the experiment once\nprint(f\"sample mean = {np.mean(y):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsample mean = 0.599\n```\n:::\n:::\n\n\n::: {#1f0fe752 .cell execution_count=10}\n``` {.python .cell-code}\ntstat, pvalue = sm.ztest(x1=y, x2=None, value=0, alternative='two-sided')\nprint(f\"t({n-1}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(9) = 2.162, p = 0.031\n```\n:::\n:::\n\n\nThe p-value we get from the parametric test is very close to the empirical p-value we computed above.\n\n## t-test for two independent samples\n\nLet's say we do an experiment and obtain two random samples of size n=10 from two different populations. We want to know if the two populations have the same mean. We can do this using a two-sample t-test.\n\n::: {#48f30baa .cell execution_count=11}\n``` {.python .cell-code}\nnp.random.seed(1234)\nn = 10\npopmean1 = 0\npopmean2 = 0\npopsd = 1\ny1 = np.random.normal(popmean1, popsd, n)\ny2 = np.random.normal(popmean2, popsd, n)\nprint(f\"The mean of the first sample is {np.mean(y1):.3f}\")\nprint(f\"The mean of the second sample is {np.mean(y2):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe mean of the first sample is -0.144\nThe mean of the second sample is 0.121\n```\n:::\n:::\n\n\n::: {#f94027eb .cell execution_count=12}\n``` {.python .cell-code}\ntstat, pvalue, df = sm.ttest_ind(y1, y2, alternative='two-sided')\nprint(f\"t({df}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(18.0) = -0.527, p = 0.605\n```\n:::\n:::\n\n\nThe p-value is above .05 and so we fail to reject the null hypothesis that the two populations have the same mean. This is what we would expect because we simulated the data from two populations with the same mean.\n\nLet's now change the mean of the second population to 1.0 and see what happens.\n\n::: {#46ce12ed .cell execution_count=13}\n``` {.python .cell-code}\nnp.random.seed(1234)\nn = 10\npopmean1 = 0\npopmean2 = 1\npopsd = 1\ny1 = np.random.normal(popmean1, popsd, n)\ny2 = np.random.normal(popmean2, popsd, n)\nprint(f\"The mean of the first sample is {np.mean(y1):.3f}\")\nprint(f\"The mean of the second sample is {np.mean(y2):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe mean of the first sample is -0.144\nThe mean of the second sample is 1.121\n```\n:::\n:::\n\n\n::: {#8c66e847 .cell execution_count=14}\n``` {.python .cell-code}\ntstat, pvalue, df = sm.ttest_ind(y1, y2, alternative='two-sided')\nprint(f\"t({df}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(18.0) = -2.517, p = 0.022\n```\n:::\n:::\n\n\nThe p-value is below .05 and so we reject the null hypothesis that the two populations have the same mean.\n\n\n## t-test for two paired samples\n\nApparently there is no paired-samples t-test in statsmodels. Scipy.stats does have one though so let's use that:\n\n::: {#6e6c7028 .cell execution_count=15}\n``` {.python .cell-code}\nnp.random.seed(1234)\nn = 10\npopmean1 = 0\npopmean2 = 0\npopsd = 1\ny1 = np.random.normal(popmean1, popsd, n)\ny2 = np.random.normal(popmean2, popsd, n)\nprint(f\"The mean of the first sample is {np.mean(y1):.3f}\")\nprint(f\"The mean of the second sample is {np.mean(y2):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe mean of the first sample is -0.144\nThe mean of the second sample is 0.121\n```\n:::\n:::\n\n\n::: {#2b27604b .cell execution_count=16}\n``` {.python .cell-code}\nimport scipy.stats as stats\ntstat, pvalue = stats.ttest_rel(y1, y2)\nprint(f\"t({n-1}) = {tstat:.3f}, p = {pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt(9) = -0.729, p = 0.484\n```\n:::\n:::\n\n\nThe p-value is above .05 and so we fail to reject the null hypothesis.\n\n## Correlation tests\n\nLet's say we have two random samples of size n=15 from two different populations. We want to know if the two populations are correlated. We can do this using a correlation test.\n\n::: {#b0af2de6 .cell execution_count=17}\n``` {.python .cell-code}\nnp.random.seed(1234)\nn = 15\npopmean1 = 0\npopmean2 = 0\npopsd = 1\ny1 = np.random.normal(popmean1, popsd, n)\ny2 = np.random.normal(popmean2, popsd, n)\nplt.figure(figsize=(4,4))\nplt.plot(y1,y2,'bs')\nplt.xlabel(\"y1\")\nplt.ylabel(\"y2\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-18-output-1.png){width=377 height=356}\n:::\n:::\n\n\n::: {#3af4bf2d .cell execution_count=18}\n``` {.python .cell-code}\nout = stats.pearsonr(y1, y2)\nprint(f\"r = {out[0]:.3f}, p = {out[1]:.3f}\")\nprint(f\"95% CI on r: {out.confidence_interval(0.95)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nr = -0.315, p = 0.252\n95% CI on r: ConfidenceInterval(low=np.float64(-0.7125755629533768), high=np.float64(0.23472947261268048))\n```\n:::\n:::\n\n\nThe p-value is above .05 and so we fail to reject the null hypothesis that the true correlation between the two populations is zero. This is what we would expect because we simulated the data from two populations with no correlation.\n\n### Role of sample size\n\nAgain as above, there is a powerful effect of sample size on the probability of obtaining large correlations *under the null hypothesis*. Let's repeat the simulations above but instead of testing sample mean against zero we will test the correlation between two random samples, under the null hypothesis in which the two samples are taken from populations with a correlation of zero.\n\n::: {#0d746d14 .cell execution_count=19}\n``` {.python .cell-code}\nsamp_sizes = [10, 50, 100, 1000]\nnsims = 10000\nfor n in samp_sizes:\n    rvalues = np.zeros(nsims)\n    for i in range(nsims):\n        y1 = np.random.normal(0, 1, n)\n        y2 = np.random.normal(0, 1, n)\n        rvalues[i] = stats.pearsonr(y1, y2)[0]\n    plt.hist(rvalues, bins=50)\nplt.xlim = (-1.1, 1.1)\nplt.legend(samp_sizes)\nplt.title(\"n=10, n=50, n=100, n=1000\")\nplt.xlabel(\"Pearson Correlation Coefficient r\")\nplt.ylabel(\"Frequency\")\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-20-output-1.png){width=662 height=470}\n:::\n:::\n\n\nWhat you can see is when the sample size is small (e.g. 10) we can expect to see a very large range of correlation coefficients *under the null hypothesis* (i.e. when the two samples are taken from populations with a true correlation equal to zero). As the sample size increases, the range of correlation coefficients shrinks.\n\nSo if we do an experiment with a small sample size, we would need to obtain a very large (far from zero) correlation coefficient in order to reject the null hypothesis that the two populations are uncorrelated.\n\n## One-way Between Subjects ANOVA\n\nLet's say we do an experiment and obtain three random samples of size n=10 from three different populations. We want to know if the three populations have the same mean. We can do this using a one-way between subjects ANOVA.\n\n::: {#d16cb472 .cell execution_count=20}\n``` {.python .cell-code}\nnp.random.seed(1234)\nn = 10\npopmean1 = 0\npopmean2 = 0\npopmean3 = 0\npopsd = 1\ny1 = np.random.normal(popmean1, popsd, n)\ny2 = np.random.normal(popmean2, popsd, n)\ny3 = np.random.normal(popmean3, popsd, n)\nprint(f\"The mean of the first sample is {np.mean(y1):.3f}\")\nprint(f\"The mean of the second sample is {np.mean(y2):.3f}\")\nprint(f\"The mean of the third sample is {np.mean(y3):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe mean of the first sample is -0.144\nThe mean of the second sample is 0.121\nThe mean of the third sample is 0.047\n```\n:::\n:::\n\n\n::: {#9d04f779 .cell execution_count=21}\n``` {.python .cell-code}\nout = stats.f_oneway(y1, y2, y3)\nprint(f\"F = {out.statistic:.3f}, p = {out.pvalue:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nF = 0.166, p = 0.848\n```\n:::\n:::\n\n\nIf we want to get a full ANOVA table in the usual way, we can use the statsmodels library. We need to create a dataframe with the data and then use the `ols` function to fit a model to the data. The `anova_lm` function then gives us the ANOVA table. This is a bit more complicated than the other tests we have seen so far but it is very flexible and can be used to do many different types of ANOVA. It is reminiscent of the `lm` function in R.\n\n::: {#0fbd4024 .cell execution_count=22}\n``` {.python .cell-code}\nimport statsmodels.api as sm\nfrom statsmodels.formula.api import ols\nimport pandas as pd\ndf = pd.DataFrame({'y': np.concatenate((y1, y2, y3)),\n                   'group': np.concatenate((np.repeat('A', n),\n                                            np.repeat('B', n),\n                                            np.repeat('C', n)))})\nmodel = ols('y ~ group', data=df).fit()\nanova_table = sm.stats.anova_lm(model, typ=3)\nprint(anova_table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              sum_sq    df         F    PR(>F)\nIntercept   0.206449   1.0  0.183477  0.671800\ngroup       0.373295   2.0  0.165878  0.848006\nResidual   30.380549  27.0       NaN       NaN\n```\n:::\n:::\n\n\n## Linear Regression\n\nWe can use `statsmodels.OLS()` to perform a linear regression using ordinary least squares to fit the model coefficients. (OLS is likely what you learned about in your introduction to statisics class(es)).\n\n::: {#0ccd65ff .cell execution_count=23}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\nimport statsmodels.api as sm\nnp.random.seed(1234)\n\nn = 11\nx = np.linspace(0, 10, n)\ny = -5 + 2*x + np.random.normal(0, 4, size=n)\n\nplt.figure(figsize=(4,4))\nplt.plot(x,y,'bo')\nplt.xlabel(\"x\")\nplt.ylabel(\"y\")\nplt.grid()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-24-output-1.png){width=374 height=374}\n:::\n:::\n\n\nWe will fit a model of the following form:\n\n$$\\hat{y_{i}} = \\beta_0 + \\beta_1 x_{i} + \\varepsilon_{i}$$\n\nwhere $\\hat{y_{i}}$ is the predicted value of $y$ for the $i$th observation, $\\beta_0$ is the model intercept, $\\beta_1$ is the model slope, and $\\varepsilon_{i}$ is the error term.\n\nFor the `statsmodels.OLS()` function we will need to add a column of ones to the x data to account for the intercept term in the model.\n\n::: {#3d1f4bf7 .cell execution_count=24}\n``` {.python .cell-code}\nX = sm.add_constant(x)\nprint(X)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[ 1.  0.]\n [ 1.  1.]\n [ 1.  2.]\n [ 1.  3.]\n [ 1.  4.]\n [ 1.  5.]\n [ 1.  6.]\n [ 1.  7.]\n [ 1.  8.]\n [ 1.  9.]\n [ 1. 10.]]\n```\n:::\n:::\n\n\n::: {#c196d2c7 .cell execution_count=25}\n``` {.python .cell-code}\nmodel = sm.OLS(y, X)\nresults = model.fit()\nprint(results.summary())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                            OLS Regression Results                            \n==============================================================================\nDep. Variable:                      y   R-squared:                       0.654\nModel:                            OLS   Adj. R-squared:                  0.616\nMethod:                 Least Squares   F-statistic:                     17.03\nDate:                Fri, 27 Mar 2026   Prob (F-statistic):            0.00257\nTime:                        14:53:35   Log-Likelihood:                -31.530\nNo. Observations:                  11   AIC:                             67.06\nDf Residuals:                       9   BIC:                             67.86\nDf Model:                           1                                         \nCovariance Type:            nonrobust                                         \n==============================================================================\n                 coef    std err          t      P>|t|      [0.025      0.975]\n------------------------------------------------------------------------------\nconst         -4.3529      2.652     -1.642      0.135     -10.352       1.646\nx1             1.8497      0.448      4.127      0.003       0.836       2.864\n==============================================================================\nOmnibus:                        0.653   Durbin-Watson:                   2.798\nProb(Omnibus):                  0.721   Jarque-Bera (JB):                0.631\nSkew:                          -0.388   Prob(JB):                        0.729\nKurtosis:                       2.120   Cond. No.                         11.3\n==============================================================================\n\nNotes:\n[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.\n```\n:::\n:::\n\n\nThe model output tells us that the intercept is -4.3529 and the slope is 1.8497. The R-squared for the model is 0.654 which tells us that 65.4 % of the variance in `y` is accounted for by `x`. The p-value for the slope is 0.003 which tells us that it is unlikely that we could have obtained a slope as large (far from zero) as we did if the samples were taken from populations for which the true slope was zero. \n\nWe can plot the model fit over the data.\n\n::: {#377b9302 .cell execution_count=26}\n``` {.python .cell-code}\nplt.figure(figsize=(4,4))\nplt.plot(x,y,'bo')\nplt.plot(x, results.predict(X), 'r-')\nplt.xlabel(\"x\")\nplt.ylabel(\"y\")\nplt.grid()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](parametric_stats_tests_files/figure-html/cell-27-output-1.png){width=374 height=374}\n:::\n:::\n\n\n## Other Resources\n\nSee the `statsmodels` documentation for more information on the various statistical tests and models available in the library. The `statsmodels` package is oriented at statisticians and so is very flexible and provides a lot of statistical information and functionality. Look over the [documentation](https://www.statsmodels.org/dev/api.html) to familiarize yourself with what is available.\n\nThe `scipy.stats` package may be easier to navigate for you for simple statistical procedures. The `scipy.stats` package is oriented at scientists and so is more focused on basic functionality needed for scientific research. Look over the [documentation](https://docs.scipy.org/doc/scipy/reference/stats.html) to familiarize yourself with what is available.\n\n",
    "supporting": [
      "parametric_stats_tests_files"
    ],
    "filters": [],
    "includes": {}
  }
}